name: GitHub Actions CI
on: [push]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Run tests and build App
        run: sh ci-build-and-tests.sh
      - name: Collect build artifacts
        if: always()
        run: |
          mkdir -p arch/macos-Release
          if [ -d "/tmp/hallelujah/build/release/hallelujah.app" ]; then
            cp -R /tmp/hallelujah/build/release/hallelujah.app arch/macos-Release/
          fi
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hallelujah-macos-Release
          path: arch/macos-Release
          retention-days: 14
