name: GitHub Actions CI
on: [push]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Run tests and build App
        run: sh ci-build-and-tests.sh
      - name: Build PKG
        run: bash package/build-package.bash
      - name: Rename PKG filename
        run: |
          PKG=$(ls /tmp/hallelujah-*.pkg | head -n1)
          mv "$PKG" /tmp/hallelujahIM.pkg
      - name: Upload PKG artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hallelujahIM-pkg
          path: /tmp/hallelujahIM.pkg
          retention-days: 14
