name: GitHub Actions CI
on: [push]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Run tests and build App
        run: sh ci-build-and-tests.sh
      - name: Build PKG
        run: bash package/build-package.bash
      - name: Upload PKG artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hallelujah-pkg
          path: /tmp/hallelujah-*.pkg
          retention-days: 14
